services:
  postgres:
    container_name: pg-order-management
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=order_management
      - PGDATA=/data/postgres